SELECT TOP(1) * FROM HR.Employees
SELECT TOP(1) * FROM Store.Suppliers
SELECT TOP(1) * FROM Store.Categories
SELECT TOP(1) * FROM Store.Products
SELECT TOP(1) * FROM Sales.Customers
SELECT TOP(1) * FROM Sales.Shippers
SELECT TOP(1) * FROM Sales.Orders
SELECT TOP(1) * FROM Sales.OrderDetails
SELECT TOP(1) * FROM Podcast.EpisodeDetails
SELECT TOP(1) * FROM Podcast.EpisodePlay